### PR TITLE
Added the Pygrok workflow digram

### PR DESCRIPTION
**Pull request by theparadoxer02**
Added the file , updated the README.md and added link if someone else want to change in the workflow diagram
.

### CODE REVIEW

**Comment by theskumar** [comment]
Probably a typo `reoad pattern`, what does this mean?

**Comment by sourabhtk37** [comment]
Link is directing to an image, but not to draw.io. Please make sure the link is to draw.io so that people can edit later.

**Comment by theparadoxer02** [comment]
@theskumar @sourabhtk37 resolved both the issues as well as squashed the commits.

**Comment by sourabhtk37** [comment]
Perfect

**Comment by sourabhtk37** [comment]
Perfect

**Comment by sourabhtk37** [comment]
Pushed to `development` branch.
Closing this PR.

**Pull request closed without merging**
